### ISSUE TITLE
Cuadro Comparativo_Nancy Olivera

### ISSUE THREAD

**Issue by Nancy-0714** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Nancy-0714#1]
Nancy Olivera Santiago.
Grupo: "1BS".
Unidad II.
Cuadro Comparativo.

![Cuadro comparativo_Nancy](https://user-images.githubusercontent.com/112412856/192425943-a86530e1-f58d-4621-b066-d6f57632b028.jpg)

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rúbrica tiene un 16% de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
